SELECT * FROM alunos
INSERT INTO alunos (nome,idade) VALUES ("Cristian soviético", 15)
INSERT INTO alunos (nome,idade) VALUES ("Arthur", 16)
INSERT INTO alunos (nome,idade) VALUES ("Guilherme", 16)
INSERT INTO alunos (nome,idade) VALUES ("João", 15)
INSERT INTO alunos (nome,idade) VALUES ("Leonardo", 15)
INSERT INTO alunos (nome,idade) VALUES ("Nicolas", 17)
INSERT INTO alunos (nome,idade) VALUES ("Pedro Alejandro", 17)
INSERT INTO alunos (nome,idade) VALUES ("Wender", 16)
INSERT INTO alunos (nome,idade) VALUES ("Arthur", 15)
INSERT INTO alunos (nome,idade) VALUES ("Emanuelle", 16)
INSERT INTO alunos (nome,idade) VALUES ("André", 16)
INSERT INTO alunos (nome,idade) VALUES ("Andressa", 16)
INSERT INTO alunos (nome,idade) VALUES ("Yasmin Angel", 17)
INSERT INTO alunos (nome,idade) VALUES ("Thauany", 16)
INSERT INTO alunos (nome,idade) VALUES ("Talita", 15)
INSERT INTO alunos (nome,idade) VALUES ("Kauany", 15)
INSERT INTO alunos (nome,idade) VALUES ("Eshillyn", 16)
INSERT INTO alunos (nome,idade) VALUES ("Izaias", 17)
INSERT INTO alunos (nome,idade) VALUES ("Breno", 16)
INSERT INTO alunos (nome,idade) VALUES ("Henrique", 16)
INSERT INTO alunos (nome,idade) VALUES ("Lucas", 17)
INSERT INTO alunos (nome,idade) VALUES ("Henrique Lima", 15)
INSERT INTO alunos (nome,idade) VALUES ("Yasmin", 15)
INSERT INTO alunos (nome,idade) VALUES ("Leonardo", 16)
INSERT INTO alunos (nome,idade) VALUES ("Rodrigo", 15)
INSERT INTO alunos (nome,idade) VALUES ("Ryan", 15)
SELECT * FROM alunos WHERE idade >= 17
SELECT * FROM alunos ORDER by matricula
SELECT * FROM alunos WHERE nome like  "%Yasmin%"
-- para aparecer sempre os nomes ou coisas parecidas na tabela, precisa usar like + (" + % + coisa a adicionar + % +")
